ElevenNote.WebMVC/Controllers/RoleController.cs
using ElevenNote.Data;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ElevenNote.WebMVC.Controllers
{
    public class RoleController : Controller
    {
        ApplicationDbContext context;

        public RoleController()
        {
            context = new ApplicationDbContext();
        }

        // GET: Role
        public ActionResult Index()
        {
            var roles = context.Roles.ToList();
            return View(roles);
        }

        public ActionResult Create()
        {
            var role = new IdentityRole();
            return View(role);
        }

        public ActionResult Create(IdentityRole role)
        {
            context.Roles.Add(role);
            context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

ElevenNote.WebMVC/Views/Role/AssignRoleToUser.cshtml
@*model Microsoft.AspNet.Identity.EntityFramework.IdentityUser*@

@{
    ViewBag.Title = "AssignRoleToUser";
}

<h2>AssignRoleToUser</h2>

@using (Html.BeginForm())
            {
                <div class="form-group">
                    @Html.Label("Select Your User Type", new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.DropDownList("UserName")
                    </div>
                </div>
                <input type="submit" value="Create Role" />
            }

ElevenNote.WebMVC/Views/Role/Create.cshtml
@model Microsoft.AspNet.Identity.EntityFramework.IdentityRole

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

<style type="text/css">
    #tbrole, .c {
        border: double;
    }
</style>

@using (Html.BeginForm())
            {
                <table class="table table-bordered table-hover">
                    <tr>
                        <td class="c">Enter Role Name To Be Created</td>
                        <td class="c">
                            @Html.EditorFor(m => m.Name)
                        </td>
                    </tr>
                </table>
                <input type="submit" value="Create Role" />
            }

ElevenNote.WebMVC/Views/Role/Index.cshtml
@model IEnumerable<Microsoft.AspNet.Identity.EntityFramework.IdentityRole>

@{
    ViewBag.Title = "Index";
}

<h2>Available Roles For Application</h2>

<section class="col-sm-6">
    <table class="table-bordered">
        @Html.ActionLink("Create Role", "Create", "Role")
    </table>
</section>

<section class="col-sm-6">
    <table class="table-bordered">
        @Html.ActionLink("Assign Role", "RegisterRole", "Account")
    </table>
</section>

<br />

<table class="table table-bordered table-hover">
    <tr>
        <th class="<">
            Role Name
        </th>
    </tr>
    @foreach(var item in Model)
            {
                <tr>
                    <td class="c">
                        @item.Name
                    </td>
                </tr>
            }
</table>